### ISSUE TITLE
Repair Permissions 

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/mactech_2014#1]
Hey Graham,

I am getting the following error on a few machines that don't have a SelfServeManifest file.

``` bash
Running installcheck_script for RepairPermissions
    Traceback (most recent call last):
      File "/tmp/munki-MzwuN2/installcheck_script", line 20, in <module>
        SelfServeManifest = plistlib.readPlist(SelfServeManifestPath)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 75, in readPlist
        pathOrFile = open(pathOrFile)
    IOError: [Errno 2] No such file or directory: '/Library/Managed Installs/manifests/SelfServeManifest'
    Running installcheck_script for RepairPermissions
    Traceback (most recent call last):
      File "/tmp/munki-MzwuN2/installcheck_script", line 20, in <module>
        SelfServeManifest = plistlib.readPlist(SelfServeManifestPath)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 75, in readPlist
        pathOrFile = open(pathOrFile)
    IOError: [Errno 2] No such file or directory: '/Library/Managed Installs/manifests/SelfServeManifest'

```

Since the check script errors MSC won't allow you to click install. I tried looking through a few articles but wasn't sure what the best approach would be. Is there an easy way to have this check_script create the SelfServeManifest plist if it doesn't exist?

**Comment by grahamgilbert** [comment]
Yes, you'd just be looking at testing if the file exists and then using plistlib to write an empty file. Not sure what your Python ability is, but it wouldn't be too difficult.

**Comment by clburlison** [comment]
Thank you for telling me to use plistlib. I knew the logic but wasn't sure what needed to be done in python (on the list of stuff to learn). Let me know if I made some dumb mistake.

**Comment by clburlison** [comment]
Looking through open issues. This is resolved.
